自定义层

In [2]:
import torch 
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,X):
        return X - X.mean()
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

作为骨架加入到更复杂·的模型

In [3]:
net = nn.Sequential(nn.Linear(8,128),CenteredLayer())
Y = net(torch.rand(4,8))
Y.mean()

tensor(1.9791e-09, grad_fn=<MeanBackward0>)

带参数的层2:34

In [9]:
class MyLinear(nn.Module):
    def __init__(self,in_units,units):
        super().__init__()
        self.weight  = nn.Parameter(torch.randn(in_units,units))
        self.bias = nn.Parameter(torch.randn(units))
    def forward(self,X):
        linear = torch.matmul(X,self.weight.data) +self.bias.data
        return F.relu(linear)
dense = MyLinear(5,3)
dense.weight

Parameter containing:
tensor([[ 0.5949,  0.6024, -0.9727],
        [-0.1419,  0.7988, -0.0295],
        [-1.1628,  0.2562,  0.0244],
        [-0.1749, -0.6404,  2.2177],
        [ 1.3132, -2.2097, -1.1137]], requires_grad=True)

In [11]:
dense(torch.rand(2,5))

tensor([[0.7184, 0.9725, 0.1082],
        [0.8055, 0.1316, 0.6607]])