加载和保存变量

In [ ]:
import torch 
from torch import nn
from torch.nn import functional as F
x= torch.arange(4)
torch.save(x,'x-file')
x2 = torch.load('x-file')
x2

In [3]:
y = torch.zeros(4)
torch.save([x,y],'x-files')
x2,y2 = torch.load('x-files')
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [4]:
mydict = {'x':x,'y':y}
torch.save(mydict,'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

加载和保存模型

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden  =nn.Linear(20,256)
        self.output =  nn.Linear(256,10)
    def forward(self,X):
        return self.output(self.hidden(X))
net = MLP()
X=  torch.randn((2,20))
Y = net(X)
print(Y)

tensor([[ 0.0493,  0.4505, -0.0378,  0.0669,  0.1562,  0.0590, -0.3653,  0.4152,
          0.4145,  0.0698],
        [-0.0784,  0.0635,  0.2395, -0.2354, -0.2125,  0.3212,  0.2062, -0.0446,
         -0.1431, -0.4469]], grad_fn=<AddmmBackward>)


In [10]:
torch.save(net.state_dict(),'mlp.params')

In [14]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [15]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])