In [2]:
import torch 
x= torch.tensor([3.0])
y =torch.tensor([2.0])
x+y

tensor([5.])

元素按照指定axis求和:消除这个维度，全部求和，axis=0是最大求和

In [12]:
a = torch.arange(20*2,dtype = torch.float32).reshape(2,5,4)
a.sum()
a_axis0=a.sum(axis=0)
a_axis2 = a.sum(axis=2)
#这里可以一步一步来
a_axis01 = a.sum(axis = [0,1]) 
 
#计算均值
mean = a.mean()
a.sum()/a.numel()

tensor(19.5000)

如果不想丢掉这个维度:这里其实是维度型归一化   触发广播机制，维度层数一致，对应维度进行复制

In [14]:
sum_a = a.sum(axis = 0,keepdims =True)
a/sum_a

tensor([[[0.0000, 0.0455, 0.0833, 0.1154],
         [0.1429, 0.1667, 0.1875, 0.2059],
         [0.2222, 0.2368, 0.2500, 0.2619],
         [0.2727, 0.2826, 0.2917, 0.3000],
         [0.3077, 0.3148, 0.3214, 0.3276]],

        [[1.0000, 0.9545, 0.9167, 0.8846],
         [0.8571, 0.8333, 0.8125, 0.7941],
         [0.7778, 0.7632, 0.7500, 0.7381],
         [0.7273, 0.7174, 0.7083, 0.7000],
         [0.6923, 0.6852, 0.6786, 0.6724]]])

In [17]:
#计算累加和
a.cumsum(axis =0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

向量乘法有两种：点积(对应元素相乘求和)和×积（矩阵相乘） 

In [34]:
#矩阵的点乘
a1 = torch.arange(4,dtype = torch.float32)
a2 = torch.ones(4,dtype =  torch.float32)
a1,a2,torch.dot(a1,a2)
#矩阵*向量
a3 = torch.ones(4,dtype = torch.float32)
a4 = torch.arange(12,dtype = torch.float32).reshape((3,4))
a3.shape,a4.shape
torch.mv(a4,a3)
#向量乘：
a5 = torch.arange(12,dtype = torch.float32).reshape((4,3))
torch.mm(a4,a5)


tensor([[ 42.,  48.,  54.],
        [114., 136., 158.],
        [186., 224., 262.]])

矩阵的范数

In [37]:
#L2范数
u = torch.tensor ([3.0,-4.0])
torch.norm(u)
#L1范数
torch.abs(u).sum()
#矩阵范数：F范数
torch.norm(a4)


tensor(22.4944)